import type { Metadata } from "next";
import React from 'react';
import Header from '../components/page-header';
import Footer from '../components/Footer';
import Providers from './providers';
import Layout from '@/components/Layout'; // Add this import

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Layout>
            <main>{children}</main>
          </Layout>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}



